version: "3.3"

services:

  postgres:
    restart: unless-stopped
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      #volumes:
      # - ./postgres-data/postgres:/var/lib/postgresql/data
      # FIXME: check is directonry mount is enough (to allow for multiple .sql
      # files initialization on modular purposes)
      # - ./dataset/extendendDoc-2021_02_25.sql:/docker-entrypoint-initdb.d/extendendDoc-2021_02_25.sql
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}

  spatial-multimedia-db:
    # image: vcity/spatial-multimedia-db-api
    build:
      context: https://github.com/VCityTeam/Spatial-Multimedia-DB-docker.git
      dockerfile: Spatial-Multimedia-DB-context/Dockerfile
    environment:
      - POSTGRES_ORDBMS=${POSTGRES_ORDBMS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - SPATIAL_MULTIMEDIA_DB_PORT=${SPATIAL_MULTIMEDIA_DB_PORT}
      - SPATIAL_MULTIMEDIA_DB_ADMIN_EMAIL=${SPATIAL_MULTIMEDIA_DB_ADMIN_EMAIL}
      - SPATIAL_MULTIMEDIA_DB_ADMIN_FIRST_NAME=${SPATIAL_MULTIMEDIA_DB_ADMIN_FIRST_NAME}
      - SPATIAL_MULTIMEDIA_DB_ADMIN_LAST_NAME=${SPATIAL_MULTIMEDIA_DB_ADMIN_LAST_NAME}
      - SPATIAL_MULTIMEDIA_DB_ADMIN_PASSWORD=${SPATIAL_MULTIMEDIA_DB_ADMIN_PASSWORD}
      - SPATIAL_MULTIMEDIA_DB_ADMIN_USERNAME=${SPATIAL_MULTIMEDIA_DB_ADMIN_USERNAME}
    ports:
      - ${SPATIAL_MULTIMEDIA_DB_PORT}:5000
    # volumes: - ./dataset/upload:/upload
    depends_on:
      - postgres

  udviz:
    # image: vcity/spatial-multimedia-db-udviz
    build:
      context: ./ud-viz-context
      args:
        SPATIAL_MULTIMEDIA_DB_FQDN: ${SPATIAL_MULTIMEDIA_DB_FQDN}
        SPATIAL_MULTIMEDIA_DB_PORT: ${SPATIAL_MULTIMEDIA_DB_PORT}
        UD_VIZ_PORT: ${UD_VIZ_PORT}
    command: node ./index.js ../UD-Viz-Template ${UD_VIZ_PORT}
    ports:
      - ${UD_VIZ_PORT}:${UD_VIZ_PORT}
